<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="jqa_ctx"
    nsURI="http://www.fluxit.com.ar/jqa/schema/rulescontext" nsPrefix="jqa_ctx">
  <eClassifiers xsi:type="ecore:EClass" name="RulesContext">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rulesContextImport" upperBound="-1"
        eType="#//RulesContextImport" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="globalPredicate" upperBound="-1"
        eType="ecore:EClass ruleset.ecore#//Predicate" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ruleSet" upperBound="-1"
        eType="ecore:EClass ruleset.ecore#//Ruleset" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="globalVariable" upperBound="-1"
        eType="#//GlobalVariable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RulesContextImport">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resource" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GlobalVariable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
</ecore:EPackage>
